### ISSUE TITLE
'~>' required_version is not supported anymore

### ISSUE THREAD

**Issue by Hellboy94520** [hashicorp/learn-terraform-provider-versioning#1]
On 'terraform init' command, following error message appear:
"""
│ Error: Unsupported Terraform Core version
│ 
│   on versions.tf line 14, in terraform:
│   14:   required_version = "~> 0.14"
│ 
│ This configuration does not support Terraform version 1.0.4. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints are normally set for good
│ reason, so updating the constraint may lead to other errors or unexpected behavior.
"""

**Comment by im2nguyen** [comment]
Thanks for reporting! Updated the configuration so it should work 😄

**Comment by Hellboy94520** [comment]
Thank you ! 👍

**Comment by DC4JG** [comment]
It looks like you missed to adapt the [website](https://learn.hashicorp.com/tutorials/terraform/provider-versioning?in=terraform/configuration-language#explore-the-workspace) accordingly. It states:

> In addition, the Terraform block specifies only Terraform binaries that are v0.14.x can run this configuration. The [~> operator](https://www.terraform.io/docs/language/expressions/version-constraints.html#gt--1) is a convenient shorthand for allowing only patch releases within a specific minor release.

this is inconsistent with `required_version = ">= 0.14"` as shown in the code block above.
